# Generated by Django 4.2 on 2024-08-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_hobby_reunion_person_hobbies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reunion',
            name='fecha',
            field=models.DateField(),
        ),
    ]
